version: "3.8"

services:
  mysqldb:
    build: ./mysql
    restart: unless-stopped
   # env_file: ./.env
   # environment:
   #   - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
   #   - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 6603:3306
   # volumes:
    #  - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
   # env_file: ./.env
    ports:
      - 6868:6060
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/diver?allowPublicKeyRetrieval=true&useSSL=false"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

#volumes:
#  db: